#!/usr/bin/perl

# MIT License

# Copyright (c) 2016 Andrew Clemons

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

use strict;
use warnings;

my %char_counts;

foreach my $line (<STDIN>) {
    chomp($line);

    foreach my $index (0..length($line) - 1) {
        my $char = substr $line, $index, 1;

        if (not defined $char_counts{$index}{$char}) {
            $char_counts{$index}{$char} = 0;
        }

        $char_counts{$index}{$char} += 1;
    }
}

my $most_common = "";
my $least_common = "";

foreach my $index (sort keys %char_counts) {
    my $hash = $char_counts{$index};

    my @sorted = sort { $hash->{$a} <=> $hash->{$b} } keys %$hash;
    my $largest = $sorted[-1];
    my $smallest = $sorted[0];

    $most_common = "$most_common$largest";
    $least_common = "$least_common$smallest"
}

print "The error-corrected version of the message being sent is $most_common\n";
print "The original message that Santa is trying to send is $least_common\n";
