#!/bin/sh

# MIT License
#
# Copyright (c) 2016-2017 Andrew Clemons
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

# shellcheck disable=SC2034
print_divider() { for divider in $(seq 1 "$1") ; do printf "%s" "$2" ; done ; printf "\n" ; }

if [ "$#" -eq 0 ] ; then
  SEQSTART=1
  SEQEND=21
elif [ "$#" -eq 1 ] && [ "x$1" != "x-h" ] ; then
  SEQSTART="$1"
  SEQEND="$1"
else
 cat << EOF
Usage: run [day#]

Runs all the puzzles or optionally the puzzle for the given day

Examples:
  ./run
  ./run 4
EOF

  exit 1
fi

for i in $(seq "$SEQSTART" "$SEQEND") ; do
  day="$(printf "day%02d\n" "$i")"

  (

    print_divider 72 "="
    printf "%s\n" "$day"

    cd "$day"

    if [ "$i" = "1" ] ; then
      ./run < input
    elif [ "$i" = "2" ] ; then
      ./run input
    elif [ "$i" = "5" ] ; then
      cargo clean
      cargo build --release --quiet
      strip --strip-unneeded "target/release/$day"
      "target/release/$day" < input
    elif [ "$i" = "13" ] || [ "$i" = "14" ] || [ "$i" = "18" ] ; then
      rm -rf target
      mkdir target

      if  [ "$i" = "14" ] ; then
        gccgo -o target/run main.go
      elif  [ "$i" = "18" ] ; then
        c++ -o target/run -O2 -Wall -Wextra main.cpp
      else
        cc -std=c11 -o target/run -O2 -Wall -Wextra main.c
      fi

      chmod +x target/run

      strip --strip-unneeded target/run

      if  [ "$i" = "14" ] || [ "$i" = "18" ] ; then
        target/run < input
      else
        zcat input.gz | target/run
      fi
    else
      if [ "$i" = "7" ] ; then
        rm -rf bin
        mkdir bin

        javac -d bin -g:none src/Main.java

        zcat input.gz | java -cp bin Main
      elif [ "$i" = "9" ] ; then
        zcat input.gz | lua run.lua
      elif [ "$i" = "15" ] ; then
        zcat input.gz | gst -f run.st
      elif [ "$i" = "16" ] ; then
        dart run.dart < input
      elif [ "$i" = "19" ] ; then
        julia run.jl < input
      else
        zcat input.gz | ./run
      fi
    fi

    print_divider 72 "="
    printf "\n"
  )
done

